# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "RevealjsGenerator"
license = "MIT"
licenselink = "https://github.com/minoritea/hugo-revealjs-generator/blob/master/LICENSE.md"
description = ""
homepage = "https://tanstaafl.0pt.jp/slides/"
tags = ["", ""]
features = ["", ""]
min_version = 0.15

[author]
  name = "Minori Tokuda"
  homepage = "https://tanstaafl.0pt.jp"
